#' energyR: Tools for Energy Consumption Analysis of Metaheuristics
#'
#' @description
#' \pkg{energyR} provides a collection of reusable R functions for loading,
#' processing, and visualising energy-consumption data generated by
#' population-based metaheuristics measured via Intel/AMD RAPL (Running Average
#' Power Limit) counters.  The package was developed to support the research
#' papers in the
#' \href{https://github.com/JJ/brave-new-green-algorithm}{Brave New Green
#' Algorithm} project, but the utilities are general enough to be used with any
#' experiment that follows the same interleaved-baseline measurement protocol.
#'
#' @section Typical workflow:
#' \enumerate{
#'   \item Load raw CSV data with \code{\link{load_bna_csv}}.
#'   \item Summarise baseline runs with \code{\link{summarize_baseline}}.
#'   \item Compute workload energy deltas with \code{\link{compute_deltas}}
#'         (separated-run design) or \code{\link{process_deltas}} (interleaved
#'         design).
#'   \item Summarise workload results with \code{\link{create_summary}}.
#'   \item Run statistical tests with \code{\link{wilcoxon_tests}}.
#'   \item Visualise with \code{\link{plot_energy_timeline}},
#'         \code{\link{plot_delta_energy}}, or \code{\link{plot_temperature}}.
#' }
#'
#' @keywords internal
"_PACKAGE"
