#' energyR: Tools for Energy Consumption Analysis of Metaheuristics
#'
#' @description
#' \pkg{energyR} provides a collection of reusable R functions for loading,
#' processing, and visualising energy-consumption data generated by
#' population-based metaheuristics measured via Intel/AMD RAPL (Running Average
#' Power Limit) counters.  The package was developed to support the research
#' papers in the
#' \href{https://github.com/JJ/brave-new-green-algorithm}{Brave New Green
#' Algorithm} project, but the utilities are general enough to be used with any
#' experiment that follows the same interleaved-baseline measurement protocol.
#'
#' @section Typical workflow:
#' \enumerate{
#'   \item Load raw CSV data with \code{\link{load_bna_csv}}.
#'   \item Optionally add derived columns:
#'     \code{\link{add_cumulative_time}},
#'     \code{\link{add_log_diff}},
#'     \code{\link{add_pop_dim_label}}.
#'   \item Remove zero-energy artefacts with \code{\link{filter_zero_energy}}.
#'   \item Summarise baseline runs with \code{\link{summarize_baseline}}.
#'   \item Compute workload energy deltas:
#'     \code{\link{compute_deltas}} (separated-run design),
#'     \code{\link{process_deltas}} (interleaved design), or
#'     \code{\link{compute_adjacent_deltas}} (adjacent-pair design).
#'   \item Optionally add covariate columns with \code{\link{process_covariates}}.
#'   \item Summarise workload results with \code{\link{create_summary}}.
#'   \item Run statistical tests with \code{\link{wilcoxon_tests}}.
#'   \item Extract ANOVA insights with \code{\link{top_anova_terms}}.
#'   \item Format for tables:
#'     \code{\link{format_mean_sd}},
#'     \code{\link{format_mean_sd_latex}},
#'     \code{\link{pivot_comparison_table}},
#'     \code{\link{energy_effort_by_fitness}}.
#'   \item Visualise with \code{\link{plot_energy_timeline}},
#'     \code{\link{plot_delta_energy}},
#'     \code{\link{plot_energy_vs_fitness}},
#'     \code{\link{plot_workload_vs_baseline}},
#'     \code{\link{plot_ridgeline_delta}}, or
#'     \code{\link{plot_temperature}}.
#' }
#'
#' @keywords internal
"_PACKAGE"

## Suppress R CMD check NOTEs for bare column names used in ggplot2 aes() calls.
## These are data-frame column names that are intentionally passed as unquoted
## symbols to aes(); they are not variables in the R global environment.
utils::globalVariables(c(
  ".data",            # rlang pronoun used in plot_ridgeline_delta
  "cum_seconds",      # plot_energy_timeline, plot_temperature, process_europar
  "PKG",              # plot_energy_timeline, plot_workload_vs_baseline, process_europar
  "delta_PKG",        # plot_delta_energy, plot_ridgeline_delta
  "work",             # plot_delta_energy, process_europar
  "initial_temp_1",   # plot_temperature
  "initial_temp_2",   # plot_temperature
  "initial_temp",     # process_europar
  "shape",            # process_europar
  "run_index",        # plot_workload_vs_baseline
  "trimmed_mean_PKG", # plot_workload_vs_baseline
  "sd_PKG"            # plot_workload_vs_baseline
))
